apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-databasing
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "database"
    objects: |
      - objectName: "db-password"
        secretPath: "secret/data/db-pass-4543"
        secretKey: "password"
      - objectName: "db-password-4554"
        secretPath: "secret/data/db-pass-44"
        secretKey: "password-4"