name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [ 'main' ]
    paths:
      - Vault-secrets/**.yaml
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in "${{ steps.files.outputs.removed }} | grep 'Vault-secrets'  ; " do
            echo "Do something with this ${changed_file}."
          done
      - run: |
          for changed_file in "${{ steps.files.outputs.added_modified }} | grep 'Vault-secrets' ; " do
            echo "Do something with this ${changed_file}."
          done