name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          echo "${{ steps.files.outputs.removed }} | grep 'Vault-secrets' "
      - run: |
          ${{ steps.files.outputs.added_modified }} | grep 'Vault-secrets' > added_modified 
          for changed_file in added_modified 
          do
            echo "Do something with this ${changed_file}."
          done