name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [ 'main' ]
    paths:
      - Vault-secrets/**.yaml
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          removed_files = '${{ steps.files.outputs.removed }}' | grep 'Vault-secrets'
          for changed_file in removed_files
          do
            echo "Do something with this ${changed_file}."
          done
      - run: |
          added_modified = '${{ steps.files.outputs.added_modified }}' | grep 'Vault-secrets'
          for changed_file in added_modified 
          do
            echo "Do something with this ${changed_file}."
          done