name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push

jobs:
  build:
    runs-on: self-hosted  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      # - uses: mikefarah/yq@master
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Get secret stored in secret/data/ci
        run: |
           pwd
           curl -H "X-Vault-Token: root" -X GET http://127.0.0.1:8200/v1/secret/data/ci

      # Example 2
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Vault-secrets/bouncer/**

      - name: Run step if any file(s) in the Vault-secret folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }} ; do 
            yq -o=json $file
          done
      # Prints the changes when done / added - Git Actions does not run when file is removed ******
      - name: Run this to read files changed in spc-yaml
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          yq ".spec.parameters.objects" ${{ steps.changed-files-specific.outputs.all_changed_files }} > object.yaml
          final_policy=""
          for val in $( yq ".[].secretPath" object.yaml ) ;
          do
              final_policy+="\n path \"${val}\" { \n \t capabilities = [\"read\"] \n } \n"
              echo $val
          done
          final_policy=\"$final_policy\"
          echo $final_policy
          cat > payload.json << EOF
          {
            "policy": ${final_policy}
          }
          EOF
          cat payload.json
          curl --header "X-Vault-Token: root" --request POST --data @payload.json http://127.0.0.1:8200/v1/sys/policy/my-policy
          rm -f object.yaml
          